services:
  node1:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node1-data:/var/opt/sqlite
    ports:
      - "8081:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE_INTERNAL: "node1:81"
      CURRENT_NODE_EXTERNAL: "localhost:8081"
      OTHER_NODE_INTERNAL.0: "node2:81"
      OTHER_NODE_EXTERNAL.0: "localhost:8082"
      OTHER_NODE_INTERNAL.1: "node3:81"
      OTHER_NODE_EXTERNAL.1: "localhost:8083"

  node2:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node2-data:/var/opt/sqlite
    ports:
      - "8082:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE_INTERNAL: "node2:81"
      CURRENT_NODE_EXTERNAL: "localhost:8082"
      OTHER_NODE_INTERNAL.0: "node1:81"
      OTHER_NODE_EXTERNAL.0: "localhost:8081"
      OTHER_NODE_INTERNAL.1: "node3:81"
      OTHER_NODE_EXTERNAL.1: "localhost:8083"

  node3:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node3-data:/var/opt/sqlite
    ports:
      - "8083:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE_INTERNAL: "node3:81"
      CURRENT_NODE_EXTERNAL: "localhost:8083"
      OTHER_NODE_INTERNAL.0: "node1:81"
      OTHER_NODE_EXTERNAL.0: "localhost:8081"
      OTHER_NODE_INTERNAL.1: "node2:81"
      OTHER_NODE_EXTERNAL.1: "localhost:8082"


volumes:
  node1-data:
  node2-data:
  node3-data: