services:
  node1:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node1-data:/var/opt/sqlite
    ports:
      - "8081:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE: node1
      OTHER_NODES: node2,node3

  node2:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node2-data:/var/opt/sqlite
    ports:
      - "8082:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE: node2
      OTHER_NODES: node1,node3

  node3:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node3-data:/var/opt/sqlite
    ports:
      - "8083:80"
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      CLIENT_PORT: 80
      RAFT_PORT: 81
      CURRENT_NODE: node3
      OTHER_NODES: node1,node2

volumes:
  node1-data:
  node2-data:
  node3-data: