services:
  node1:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node1-data:/var/opt/sqlite
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      HTTP_PORT: 80
      CURRENT_NODE: node1
      OTHER_NODES: node2,node3

  node2:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node2-data:/var/opt/sqlite
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      HTTP_PORT: 80
      CURRENT_NODE: node2
      OTHER_NODES: node1,node3

  node3:
    image: "kvstore:0.1.0-SNAPSHOT"
    volumes:
      - node3-data:/var/opt/sqlite
    environment:
      SQLITE_DB_PATH: "/var/opt/sqlite/key.db"
      SQLITE_FETCH_SIZE: 100
      HTTP_PORT: 80
      CURRENT_NODE: node3
      OTHER_NODES: node1,node2

  proxy:
    image: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    configs:
      - source: default.conf
        target: /etc/nginx/conf.d/default.conf

configs:
  default.conf:
    content: |
      upstream backend {
        server node1:80;
        server node2:80;
        server node3:80;
      }

      server {
        listen 80;

        include /etc/nginx/mime.types;

        proxy_redirect //node1:80/ http://localhost:8080/1/;
        proxy_redirect //node2:80/ http://localhost:8080/2/;
        proxy_redirect //node3:80/ http://localhost:8080/3/;

        location / {
          proxy_pass http://backend/;
        }
        location /1/ {
          proxy_pass http://node1:80/;
        }
        location /2/ {
          proxy_pass http://node2:80/;
        }
        location /3/ {
          proxy_pass http://node3:80/;
        }
        location ~ /(1|2|3)/raft {
          deny all;
          return 403;
        }
        location ~ /raft {
          deny all;
          return 403;
        }
      }

volumes:
  node1-data:
  node2-data:
  node3-data: